conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
    default_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    gap_x = 100,
    gap_y = 4,
    minimum_height = 100,
    minimum_width = 1800,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    override_utf8_locale = true,
    update_interval = 900,
    use_xft = true,
    xftalpha = 1,
    font = 'Bitcount Grid Single Roman:size=20',
}

conky.text = [[
${scroll 120 ${execpi 900 python3 ~/.config/conky/weather_fetch.py}}
]]